title: Preetish Javalgekar  # your name (or website title) here
logo: "/ProfilePhoto-modified.png" #?raw=true # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Lead Software Development Engineer
  <br><br>
  <a href="mailto:jpreetish@gmail.com">jpreetish@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/preetish-javalgekar/">LinkedIn Profile</a>
  <br>
  <a href="https://github.com/jpreetish">Github</a> 
theme: jekyll-theme-minimal
